export { default as LoginPage } from './auth/LoginPage'
export { default as SignUpPage } from './auth/SignUpPage'
export { default as ForgotPasswordPage } from './auth/ForgotPasswordPage'
export { default as HomePage } from './home/HomePage'
export { default as RoleSignUpPage } from '@/pages/publicPages/auth/RoleSignUpPage'
export { default as About } from './about/AboutPage'
export { default as ProductDetail } from './productDetail/ProductDetailPage'
